- name: Configure CBS for Ceph mimic
  hosts: localhost
  gather_facts: false
  vars:
    ceph_codename: mimic
    cbs_arches: x86_64 aarch64 ppc64le
    cbs_candidate_tag: storage7-ceph-{{ ceph_codename }}-candidate
    cbs_testing_tag: storage7-ceph-{{ ceph_codename }}-testing
    cbs_release_tag: storage7-ceph-{{ ceph_codename }}-release
    cbs_build_tag: storage7-ceph-{{ ceph_codename }}-el7-build
    cbs_build_target: storage7-ceph-{{ ceph_codename }}-el7
    build_inheritance:
    - parent: buildsys7
      priority: 5
    - parent: "{{ cbs_candidate_tag }}"
      priority: 10
    - parent: storage7-ceph-common-candidate
      priority: 15
    - parent: storage7-common-candidate
      priority: 20
    # https://bugs.centos.org/view.php?id=15700
    - parent: sclo7-devtoolset-7-rh-candidate
      priority: 25
    external_repos:
    - repo: centos7-cr
      priority: 5
    - repo: centos7-extras
      priority: 10
    - repo: centos7-updates
      priority: 15
    - repo: centos7-os
      priority: 20
    packages:
      ktdreyer:
      - CUnit
      - babeltrace
      - ceph
      - ceph-ansible
      - jq
      - leveldb
      - libntirpc
      - lttng-ust
      - nfs-ganesha
      - oath-toolkit
      - oniguruma
      - pytest
      - python-attrs
      - python-bcrypt
      - python-funcsigs
      - python-logutils
      - python-more-itertools
      - python-notario
      - python-pecan
      - python-pluggy
      - python-prettytable
      - python-py
      - python-repoze-lru
      - python-routes
      - python-simplegeneric
      - python-singledispatch
      - python-six
      - rook
      - userspace-rcu
      - xmlstarlet
      - yasm
    build_group_packages:
    - bash
    - buildsys-macros-el7
    - buildsys-tools
    - bzip2
    - coreutils
    - cpio
    - curl
    - diffutils
    - findutils
    - gawk
    - gcc
    - gcc-c++
    - grep
    - gzip
    - info
    - make
    - patch
    - redhat-release
    - redhat-rpm-config
    - rpm-build
    - sed
    - shadow-utils
    - tar
    - unzip
    - util-linux-ng
    - which
  roles:
  - cbs
